### DISCUSSION TITLE
Help setting up DDEV in CircleCI?

### DISCUSSION THREAD

**Discussion by timstallmann** [ddev/ddev#3219] [Q&A] [answered]
Hi! 

There's a brief mention in the docs of using DDEV in CircleCI to spin up a site but no sample configuration; I'd love to try this approach so I can just re-use ddev to spin up the site in test environment, but need some help!

I'm getting stuck on how to actually run ddev -- CircleCI seems to [require you to run docker commands in a remote executor environment](https://circleci.com/docs/2.0/building-docker-images/#overview) which doesn't have the same filesystem binding as a local docker instance would; so when I get to the `ddev start` step and ddev is spinning up containers, I get a lot of the following errors:

`ERROR: for ddev-project-db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /home/circleci/repo/.ddev`

Here's what the circleci config looks like:

```yml
version: 2
jobs:
  build:
    docker:
      - image: cimg/php:7.4-browsers

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.6

      - run:
          name: Install ddev
          command: |
            curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh

      - run:
          name: Start server running
          command: |
            ddev start -y
```

Any thoughts on this? I'd be happy to post a sample working config so it can be linked in the docs once I get it working..
