### DISCUSSION TITLE
Support multiple environments with one provider configuration

### DISCUSSION THREAD

**Discussion by dahaupt** [ddev/ddev#3315] [Ideas]
Currently we have two remote environments: Staging and Production. We run the project on a shared hosting server (powered by Plesk). The two environments are simply located in two different directories.

Based on the current [documentation](https://ddev.readthedocs.io/en/stable/users/providers/provider-introduction/) we created two provider configurations to pull both environments with `ddev pull`. The only difference between the two configuration files (`staging.yaml` and `production.yaml`) is the environment variable `projectRoot`.

Therefore, in our case it would be great if this could be implemented with only one provider configuration (e.g. only `plesk.yaml` or `remote.yaml`).

Suggestion: 
```
ddev pull plesk --env=staging
```

`plesk.yaml`:
```
environment_variables:
  phpBin: /opt/plesk/php/7.4/bin/php
 
environments:
  staging:
    projectRoot: /path/to/staging/project/
  production:
    projectRoot: /path/to/production/project/

db_pull_command:
  command: |
    # set -x   # You can enable bash debugging output by uncommenting
    set -eu -o pipefail
    # Fetch database with variable ${projectRoot} provided by enviroment configuration
  service: web
```

Looking forward to your feedback!
