### DISCUSSION TITLE
How to get service compatibility v1.18 *and* v1.19+ (networks)

### DISCUSSION THREAD

**Discussion by jonaseberle** [ddev/ddev#3514] [Q&A]
Being able to prepare services that won't break ddev with v1.19 will be a huge help.
I'll open this thread here to play with ideas and have people test what we can come up with.

With https://github.com/drud/ddev/pull/3510 there will be a better message to tell users that services need to be upgraded.
This also signals that we are *requiring* at least networks "default" + "ddev" on all services now to have an easier time detecting a missing upgrade and with supporting problems.

I have tried to make services "v1.19-ready" in v1.18 already and this is what I have come up with:

In your `docker-compose.<service>.yaml`:
```
services:
  <service>:
    ...
    networks: [default, ddev]

networks:
  # for ddev v1.18 compatibility
  ddev:
    external: true
```

In your `.ddev/config.yaml`:
```
hooks:
  # for ddev v1.18 compatibility
  pre-start:
  - exec-host: docker network create ddev || true
```

This is only tested on Linux though. I would be happy to get some feedback if we would need changes in your environment.
A note for testing: Run `ddev start` *twice* since I might have found a problem where changes to .yaml files are only picked up the second time.

**Comment by rfay** [comment]
Another step would be to rename "ddev" back to "ddev_default". Then the network itself wouldn't have to be created. Obviously I didn't know how disruptive that name change would be.

**Reply by rfay** [reply]
This change is now in there. It may make this part easier to navigate.

**Reply by jonaseberle** [reply]
Should we add the 
```
networks:
  # for ddev v1.18 compatibility
  ddev_default:
    external: true
```
to all service examples in ddev-contrib and docs?

Or is that a bit over the top because it will only be relevant for the few weeks until everybody updated?
