### DISCUSSION TITLE
Additional database configurations

### DISCUSSION THREAD

**Discussion by brandonkelly** [ddev/ddev#3926] [Ideas]
There are times when a single project needs to be able to connect to multiple database types/versions at the same time.

For example, Craft CMS supports both MySQL/MariaDB and PostgreSQL, and we need to be able to run tests across both simultaneously.

It would be awesome if this was possible out of the box with DDEV. Perhaps configured using a new `additional_databases` setting, like so:

```yaml
database:
  type: mariadb
  version: "10.3"
additional_databases:
  pg:
    type: postgres
    version: "14"
```

The keys would define the additional databases’ names, which could be used in place of `db` for the container name (e.g. `ddev-myproject-pg`), and perhaps for the username/password as well.
