### DISCUSSION TITLE
Mutagen: ignore paths specified by gitattributes export-ignore

### DISCUSSION THREAD

**Discussion by brandonkelly** [ddev/ddev#3936] [Ideas]
It would be really cool if DDEV could automatically configure Mutagen to ignore paths specified to be excluded by `.gitattributes` files within the project, via [export-ignore](https://git-scm.com/docs/gitattributes#_export_ignore) directives.

I’m imagining this would be opt-in, via a new `sync.defaults.ignore.gitattributes` setting:

```yaml
sync:
  defaults:
    mode: "two-way-resolved"
    stageMode: "neighboring"
    ignore:
      gitattributes: true
      paths:
        - ...
```

With that enabled, if a project has a `lib/x/.gitattributes` file with the following:

```sh
/src/web/assets/**/src export-ignore
```

DDEV could then see that file, parse it for `export-ignore` lines, and add the following to Mutagen’s `sync.defaults.ignore.paths` array:

- `lib/x/src/web/assets/**/src`
