### DISCUSSION TITLE
Is there a difference between these two ways of exposing ports?

### DISCUSSION THREAD

**Discussion by joshuapease** [ddev/ddev#4538] [Q&A] [answered]
I've seen two ways of exposing extra ports in DDEV (for something like Vite or Webpack dev servers). 

The first is through `web_extra_exposed_ports`

```
web_extra_exposed_ports:
  - name: vite
    container_port: 3000
    http_port: 3000
    https_port: 3001
```

The other is creating a custom `/.ddev/docker-compose.*.yaml` file.

```
# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE services
# to expose port `3000` of DDEV's web container.
version: '3.6'
services:
  web:
    expose:
      - '3000'
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,3001:3000
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,3000:3000
```

Is there functionally any difference between the two? 

I tend to prefer `web_extra_exposed_ports` but wanted to make sure I wasn't missing some obvious difference between the two.

Thanks a ton!
