### DISCUSSION TITLE
How to get the $uid / $gid variables in custom docker compose services?

### DISCUSSION THREAD

**Discussion by deviantintegral** [ddev/ddev#4733] [Q&A]
We've been extending a project with additional ddev services, most recently with [ZAP](https://owasp.org/www-project-zap/). In this case, we want to bind-mount in a directory to save reports generated by the scan. By default, this image (and others I've worked with) have UIDs set to something like `1000`.

I thought we could fix this with:

```
  zap-bare:
    container_name: ddev-${DDEV_SITENAME}-zap-bare

    build:
      context: zap-bare-build
...
```

And then:

```
FROM owasp/zap2docker-bare:2.12.0

USER root
RUN apk add -u shadow
RUN usermod -u $uid zap
RUN groupmod -g $gid zap
RUN find / -uid 1000 -exec chown -h $uid {} +
RUN find / -gid 1000 -exec chgrp -h $gid {} +
USER zap
```

However, looking at `.ddev/.ddev-docker-compose-full.yaml`, only the web and database containers have uid / gid args passed in:

```
    db:
        build:
            args:
                BASE_IMAGE: drud/ddev-dbserver-mariadb-10.6:v1.21.5
                gid: "20"
                uid: "501"
                username: andrew
```

Since these values are per-host, is there any way to get ddev to include these three values in all compose services?
