### DISCUSSION TITLE
How to get Traefik to route to dynamic hostname and port mappings?

### DISCUSSION THREAD

**Discussion by lpeabody** [ddev/ddev#5619] [Q&A]
I don't understand well enough the mechanism used to calculate the services and routers that Traefik uses to direct requests to containers. Hopefully y'all can help me sort that out.

Hard requirements:
- Multiple instances of this project must be able to run at the same time on the same system.
- Primary domain must map to the react app (whatever service is running it).
- Documentation domain serves a static HTML website on domain `docs-primary-domain`.

We have a React app that we run and should be able to access through the DDEV site's default domain (generated based on the project directory name). The React app runs on port 3000, so, `https://primary-domain.ddev.site` should bring up the React app when its running.

We also have a static documentation site that should be accessible at `https://docs-primary-domain.ddev.site`.

Both off these sites are currently served through the `web` service.

Typically the way I would do this with Traefik would be something like:

```
services:
  web:
      labels:
          - traefik.http.routers.react-router.rule=Host($DDEV_HOSTNAME)
          - traefik.http.routers.react-router.service=react-service
          - traefik.http.services.react-service.loadbalancer.server.port=3000
          - traefik.http.routers.docs-router.rule=Host(docs-$DDEV_HOSTNAME)
          - traefik.http.routers.docs-router.service=docs-service
          - traefik.http.services.docs-service.loadbalancer.server.port=80
```

So, this would serve the documentation site through `https://docs-DDEV_HOSTNAME`, and the react application through `https://DDEV_HOSTNAME`.

In this way, I'd be able to access the docs site web server service and the react application service from every instance of my project running locally, with DDEV_HOSTNAME calculated dynamically based on the project directory.

However, given DDEV's implementation of the Traefik router, it's completely unclear to me how to accomplish something similar using a hardcoded file configuration. It might be and I just don't know what the algorithm is that produces that file (I checked to see if it's well documented but I so far haven't read anything that would indicate how to do this).

Does anyone have any pointers? Thanks in advance.
