### DISCUSSION TITLE
Use ddev router for service on host

### DISCUSSION THREAD

**Discussion by woldtwerk** [ddev/ddev#6854] [Q&A]
How do I proxy a host service (not in docker or ddev)?

e.g. on host: localhost:8080

~/.config/ddev/traefik/config/extra.yaml:
```yaml
http:
  routers:
    php83:
      entrypoints:
        - http-80
      rule: "Host(`83.php.localhost`)"
      service: php83
      tls: false
    php83-https:
      entrypoints:
        - http-443
      rule: "Host(`83.php.localhost`)"
      service: php83
      tls: true
  services:
    php83:
      loadbalancer:
        servers:
          - url: http://host.docker.internal:8080
          # - url: http://localhost:8080
```

~/.config/ddev/router-compose.custom.yaml
```yaml
services:
  ddev-router:
    extra_hosts:
      - host.docker.internal=host-gateway
```
