### DISCUSSION TITLE
Routing for Drupal multisite

### DISCUSSION THREAD

**Discussion by lpeabody** [ddev/ddev#7111] [Ideas]
# Use Case

My use case for this feature is supporting Drupal multisite. For example, I have a project name of `my-drupal-project`. I want `my-drupal-project.ddev.site` to go to the `default` Drupal site, and `other-site-my-drupal-project.ddev.site` to go to the `other_site` Drupal site.

# Related info

I like to setup my DDEV projects so the `name` configuration value is not set directly in a YAML file. So, it is dynamically determined based on the name of the directory the DDEV project sits in. This allows me to simultaneously run the same project side by side on the same host simply by dropping the same codebase into different directories.

# Possible approach

In the use case given, the project name is `my-drupal-project`. DDEV takes this and uses it to calculate the reverse proxy routing rules. To satisfy the use case, I would like DDEV to set the rule such that `my-drupal-project.ddev.site` is matched as well as `other-site-my-drupal-project.ddev.site`. Looking at the project's generated Traefik config file, the rule looks like the following:

```yaml
rule: HostRegexp(`^my-drupal-project\.ddev\.site$`)
```

an alternative to this that would satisfy my requirement would be to simply remove the opening caret:

```yaml
rule: HostRegexp(`my-drupal-project\.ddev\.site$`)
```

Maybe a boolean configuration flag could be introduced for enabling or disabling the incorporation of the caret? Something like...

```yaml
enable_open_host_prefixes: true
```

...where a `false` value prefixes the regex rule with a caret, and `true` omits the caret. Default would be `false` for backwards compatibility reasons.

**Comment by rfay** [comment]
Drupal's primary routing technique is often via the hostname.

You already know that you can configure multiple hostnames, right, with `additional_hostnames` and `additional_fqdns` ?

And you already know that you can omit the hostname from a project's config.yaml and it will use the directory name?

And you already know about the classic setup for drupal multisite in https://github.com/ddev/ddev-contrib/tree/master/recipes/drupal8-multisite ?

It's not clear to me how your needs aren't already met by `additional_hostnames` and a possible sites.php file. Please continue the conversation!

**Reply by lpeabody** [reply]
I'm aware of these features but perhaps uncertain of how to leverage them in order to meet my use case.

Assume I have multiple copies of the project running on my host (developing multiple features in parallel). Let's say I have two versions of the project running on my system: `project-a-copy`, `project-b-copy`. There are two site directories: `default`, and `other_site`.

- `project-a-copy` Docker Compose environment:
    - `default`: `https://project-a-copy.ddev.site`
    - `other_site`: `https://other-site-project-a-copy.ddev.site`
- `project-b-copy` Docker Compose environment:
    - `default`: `https://project-b-copy.ddev.site`
    - `other_site`: https://other-site-project-b-copy.ddev.site`

crude project `sites.php`:

```php
if (getenv('IS_DDEV_PROJECT')) {
  $ddev_project = getenv('DDEV_PROJECT');
  $ddev_tld = getenv('DDEV_TLD');
  $ddev_virtual_host = "$ddev_project.$ddev_tld";
  $ddev_multisite_map = ['local_test']; // Can easily replace with getting all directories in web/sites while excluding default
  foreach ($ddev_multisite_map as $site_dir) {
    $prefix = str_replace('_', '-', $site_dir);
    $site_domain = "$prefix-$ddev_virtual_host";
    $sites[$site_domain] = $site_dir;
  }
}
```

If the caret is omitted in the regex host matching, then I can spin up as many parallel versions of the project I need while ensuring that I have a consistent URL pattern for accessing every multisite in the project.

In the drupal8 multisite repo you linked (I had looked at this btw), it uses `additional_hostnames`:

```yaml
additional_hostnames:
  - basic
  - umami
```

This is incompatible with running parallel versions of the same project - the Traefik router won't know which Docker Compose environment to route `basic.ddev.site` to. Using `additional_fqdns` you run into the same issue.

**Reply by rfay** [reply]
If I understand right, you're asking that two separate projects, both multisite, behave correctly with both running at the same time?

The first answer would be stop one and start the other, I would think.

Additional answers would be to make your sites.php more sophisticated.

And of course I think you already know that you can extend the project traefik config to meet your needs, but that's more complex than most people should ever deal with.

**Reply by lpeabody** [reply]
> The first answer would be stop one and start the other, I would think.

Speaking for myself, I would like to be able to run all of my projects simultaneously if I am not constrained by system resources. I want to be able to jump back and forth if I need to. Without starting and stopping. Like if I'm giving a live demo, I don't want to spend time spinning down and starting up.

> Additional answers would be to make your sites.php more sophisticated.

Unsure of what this looks like. You need to be able to leverage information within the Docker Compose environment to calculate the site patterns to add to `$sites`. Can you give an example of what you're thinking here?

> And of course I think you already know that you can extend the project traefik config to meet your needs, but that's more complex than most people should ever deal with.

I'm assuming you're referring to being able to place additional YAML configuration files in `.ddev/traefik/config`? I had considered this but I'm unsure of how to write the router rule such that it is unique per project instance?

**Reply by rfay** [reply]
Per-project traefik configuration is described in https://ddev.readthedocs.io/en/stable/users/extend/traefik-router/#project-traefik-configuration

Another tool in your toolbox would be `ddev stop --unlist`, which removes the registration from ddev but doesn't delete the database or anything. (That doesn't help you with running both at same time)

Mostly it seems to me like you have very complex requirements and you have the tools to solve them, but you're going to have to use all the tools. You might be able to do it with just extensive sites.php thinking.

**Reply by lpeabody** [reply]
> Mostly it seems to me like you have very complex requirements and you have the tools to solve them

Within the constraints I've specified I'm not sure if DDEV provides all of the tooling necessary. I would argue that the requirements I've specified, at least within the context of containerization principals (https://12factor.net/config), is not complex but more expected behavior from a containerized application. In the 12 factor example, to use the QA environment you wouldn't be expected to first shut down the Staging environment.

I get that DDEV is a specialized use of containerization, but I like to think there is somewhere you're willing to meet in the middle? Maybe the `enable_open_host_prefixes: true` is not the best approach? What if a project could customize the template (https://github.com/ddev/ddev/blob/main/pkg/ddevapp/traefik_config_template.yaml) used to generate the project's Traefik configuration?

**Reply by rfay** [reply]
You may misunderstand DDEV. It is not a Kubernetes application to be deployed as a container or something using 12-factor. It's a local development toolkit. It's very opinionated, aimed at people being successful with local development. 

I think you can understand that we can't create new code for every specific configuration, which is why we give you so very many tools, including the ability to even change your project's traefik configuration. And of course Drupal itself gives you many tools, including a sophisticated sites.php. IMO you should be able to solve what I understand of your challenge using a `config.local.php` for each project (with additional_hostnames perhaps), and a `sites.php` that maps the proper hostnames. Note that sites.php can have lots of mappings in it, you may not even have to have anything but a list of the various things all your different projects use.

**Reply by lpeabody** [reply]
> It's very opinionated, aimed at people being successful with local development.

Not arguing against opinionated tooling :) Its required to deliver quality solutions.

> It is not a Kubernetes 

Correct it is not, but it is Docker Compose and the principals of 12 factor can still apply. It would be really nice to be able ship a project backed by DDEV that just worked without the need for additional manual configuration that must be applied each time you bring up the project's environment.

Another approach I had considered is tapping into DDEV's hook system to generate on-the-fly configuration files to set `additional_hostnames` based on the project name. Is that possible? The configuration would need to be generated and then immediately applied (i.e. not have to run `ddev start` a second time to apply the configuration that was just generated).

For example:

1. `ddev start`
2. Some hook runs (not sure which one) that generates `.ddev/config.project_multisite_hostnames.yaml`
3. The configuration generated is applied within the `ddev start` process immediately

Is that possible?

**Reply by rfay** [reply]
Yes of course, using `config.*.yaml` as you wish is super easy. I even suspect that you could add a pre-start exec-host hook that would create your `config.*.yaml` based on the project name. No guarantees.

You could also make wrapper scripts that could do that (and use those instead of `ddev start`)

**Reply by lpeabody** [reply]
I added the following to do a quick test:

```yaml
hooks:
  pre-start:
    - exec-host: |
        cat > .ddev/config.multisite_hosts.yaml <<EOL
        additional_hostnames:
          - local-test-site

        EOL
```

I also did the following:

1. `ddev powerdown`
2. Delete the `.ddev/traefik` directory.
3. `ddev start`

This resulted in the following Traefik config file being generated:

```yaml
#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    polymer-drupal-pantheon-testing-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^polymer-drupal-pantheon-testing\.ddev\.site$`)
      
      service: "polymer-drupal-pantheon-testing-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "polymer-drupal-pantheon-testing-redirectHttps"
    polymer-drupal-pantheon-testing-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^polymer-drupal-pantheon-testing\.ddev\.site$`)
      
      service: "polymer-drupal-pantheon-testing-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "polymer-drupal-pantheon-testing-redirectHttps"
    polymer-drupal-pantheon-testing-web-81-http:
      entrypoints:
        - http-81
      rule: HostRegexp(`^polymer-drupal-pantheon-testing\.ddev\.site$`)
      
      service: "polymer-drupal-pantheon-testing-web-81"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "polymer-drupal-pantheon-testing-redirectHttps"
    
    
    
    
    polymer-drupal-pantheon-testing-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^polymer-drupal-pantheon-testing\.ddev\.site$`)
      
      service: "polymer-drupal-pantheon-testing-web-80"
      ruleSyntax: v3
      
      tls: true
      
    polymer-drupal-pantheon-testing-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^polymer-drupal-pantheon-testing\.ddev\.site$`)
      
      service: "polymer-drupal-pantheon-testing-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    polymer-drupal-pantheon-testing-web-81-https:
      entrypoints:
        - http-444
      rule: HostRegexp(`^polymer-drupal-pantheon-testing\.ddev\.site$`)
      
      service: "polymer-drupal-pantheon-testing-web-81"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    polymer-drupal-pantheon-testing-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    polymer-drupal-pantheon-testing-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-polymer-drupal-pantheon-testing-web:80
        
    polymer-drupal-pantheon-testing-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-polymer-drupal-pantheon-testing-web:8025
        
    polymer-drupal-pantheon-testing-web-81:
      loadbalancer:
        servers:
          - url: http://ddev-polymer-drupal-pantheon-testing-web:81
        
    
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/polymer-drupal-pantheon-testing.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/polymer-drupal-pantheon-testing.key
```

It looks like the additional host names weren't added. However, running `ddev status` lists the extra host names:

```
├──────────────┼──────┼──────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ Project URLs │      │ https://polymer-drupal-pantheon-testing.ddev.site,                           │                    │
│              │      │ https://local-test-site.ddev.site, https://127.0.0.1:33353,                  │                    │
│              │      │ http://polymer-drupal-pantheon-testing.ddev.site,                            │                    │
│              │      │ http://local-test-site.ddev.site, http://127.0.0.1:33351                     │                    │
└──────────────┴──────┴──────────────────────────────────────────────────────────────────────────────┴────────────────────┘
```

So, there is a discrepancy between what is actually applied in the environment vs what the configuration actually says. Should this be the case? Is it a bug?
