### DISCUSSION TITLE
How to configure a global mount for all DDEV projects in the $HOME/.ddev directory?

### DISCUSSION THREAD

**Discussion by MurzNN** [ddev/ddev#7149] [Q&A] [answered]
I need to configure a global mount directory to all projects, is it possible?
Now I need to configure it separately in each ddev project by creating a file `.ddev/docker-compose.my-mounts.yaml`:
```yaml
services:
  web:
    volumes:
      - "./homemounts/.vscode-server:/home/alexey_korepov/.vscode-server"
      - "$HOME/.local/bin:/home/alexey_korepov/.local/bin"
      - "$HOME/.cache/vscode/containers-bin:/home/alexey_korepov/.vscode-server/bin"
      - "$HOME/.cache/vscode/extensionsCache:/home/alexey_korepov/.vscode-server/extensionsCache"
```

But want to configure this only once and apply to all projects. Is it possible?
