### DISCUSSION TITLE
DDEV + OrbStack Network Conflict Preventing Node.js Service Start - Seeking Help!

### DISCUSSION THREAD

**Discussion by wmurfee** [ddev/ddev#7276] [Q&A] [answered]
Hi everyone,

I've been wrestling with getting a Node.js service to run alongside my existing PHP (ExpressionEngine) DDEV project while using OrbStack as my Docker provider. I've encountered a persistent network conflict error that's preventing the Node.js container from starting correctly, and I'm hoping someone in the community might have some insights.

### My Setup:

Operating System: macOS Sequoia 15.4.1
DDEV Version: 1.24.4
OrbStack Version: 1.10.3
PHP Version: 8.3

### Goal:

To run a separate Node.js server within the same DDEV project, accessible via a specific path (/api) using Traefik.

What I've Done So Far:

Created .ddev/docker-compose.override.yaml:

**YAML**

```
version: '3.6'
services:
  nodejs:
    container_name: ddev-${DDEV_SITENAME}-node
    image: node:20
    working_dir: /app
    volumes:
      - .:/app:rw,delegated
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=PathPrefix(`/api`)"
      - "traefik.http.services.node.loadbalancer.server.port=3000"
      - "traefik.http.routers.node.entrypoints=http,https"
    command: node server/server.js
    depends_on:
      - web
    networks:
      - default

networks:
  default:
    name: ddev-${DDEV_SITENAME}_default
    external: true
```

My Node.js server folder and server.js file are confirmed at the root of my project.

Encountered `"Cannot find module '/app/server/server.js'" error`: Initially, the Node.js container would start but immediately crash with this error. This suggests a problem with the volume mount or the working directory.

Tried ddev ssh -s nodejs: This consistently failed with the error: `ddev ssh failed: service nodejs is not running in project testingproject (state=doesnotexist), even though the container appeared to be running in OrbStack (though often exiting quickly due to the "cannot find module" error).`

Simplified command for testing: Changed the command to `tail -f /dev/null` to keep the container running. With this, the container stayed up, but `ddev ssh -s nodejs` still failed.

Checked DDEV logs: The logs consistently showed the "Cannot find module" error when the original command was used.

Tried a minimal testnode service: In a fresh DDEV project with OrbStack, a minimal docker-compose.override.yaml like this also failed ddev ssh:

**YAML**

```
version: '3.6'
services:
  testnode:
    image: node:20
    command: tail -f /dev/null
```

Error: `ddev ssh failed: service testnode is not running in project testingproj (state=doesnotexist)`

Tried nginx:alpine: A minimal service using nginx:alpine worked and was accessible in the browser, indicating that DDEV and OrbStack can run basic custom services. However, switching back to node:20 leads to the original issues.

Encountered OrbStack network conflict: The OrbStack debug output shows: create container: [Docker] Container cannot be created with multiple network endpoints: ddev-jtcc-fastspot_default, ddev_default.

Explicitly defined networks in docker-compose.override.yaml: Added the networks section as shown in the first step. This did not resolve the OrbStack network conflict.

Tried removing ddev_default network: docker network rm ddev_default failed due to active endpoints.

Stopped and removed all DDEV containers and networks: Used docker stop, docker rm, and docker network rm to clean up. The OrbStack network conflict still persists after ddev restart.

### Current Status:

The OrbStack debug output consistently shows the network conflict, preventing the nodejs container from being created correctly in a way that DDEV recognizes for ddev ssh. The "Cannot find module" error is likely a secondary issue that would need to be addressed once the container is running properly.

### Seeking Help:

Has anyone encountered this error with DDEV and OrbStack? This was also the case when trying on Docker desktop. Are there any specific OrbStack configurations or DDEV settings that might be causing this conflict? Any insights or suggestions on how to resolve this would be greatly appreciated!

Thanks in advance for your help!
