### DISCUSSION TITLE
Configure mysql 8.4 with "mysql_native_password"

### DISCUSSION THREAD

**Discussion by RPotkowaVegasystems** [ddev/ddev#7384] [Q&A]
I need to use the "mysql_native_password", how can i configure ddev to use it?

**Comment by stasadev** [comment]
Hi @RPotkowaVegasystems,

DDEV projects using PHP 5.6-7.3 with MySQL 8.0 and 8.4 default to `mysql_native_password`.
DDEV projects using PHP 7.4+ with MySQL 8.0 or 8.4 default to `caching_sha2_password`.

To enforce `mysql_native_password` for all PHP versions, create `.ddev/config.mysql.yaml`:

```yaml
hooks:
  post-start:
    - exec: mysql -e "ALTER USER 'db'@'%' IDENTIFIED WITH mysql_native_password BY 'db';"
      service: db
    - exec: mysql -e "ALTER USER 'db'@'localhost' IDENTIFIED WITH mysql_native_password BY 'db';"
      service: db
    - exec: mysql -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';"
      service: db
    - exec: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
      service: db
```

Run `ddev restart` and verify with:

```
$ ddev mysql -e 'SELECT user, host, plugin FROM mysql.user;'
+------------------+-----------+-----------------------+
| user             | host      | plugin                |
+------------------+-----------+-----------------------+
| db               | %         | mysql_native_password |
| root             | %         | mysql_native_password |
| db               | localhost | mysql_native_password |
| mysql.infoschema | localhost | caching_sha2_password |
| mysql.session    | localhost | caching_sha2_password |
| mysql.sys        | localhost | caching_sha2_password |
| root             | localhost | mysql_native_password |
+------------------+-----------+-----------------------+
```

Note: `mysql_native_password` will be [removed](https://dev.mysql.com/doc/refman/8.4/en/native-pluggable-authentication.html) in MySQL 9.0.
