### ISSUE TITLE
variables in provider environment_variables don't get properly evaluated if the value has spaces in it

### ISSUE THREAD

**Issue by schliesser** [ddev/ddev#3499]
**Describe the bug**

String variables with space are not correctly transferred from yaml to bash.

**To Reproduce**

* Create a custom provider configuration
* Add a variable which contains a space in the value
* Use the variable in a command

```yaml
environment_variables:
  test: "variable with spaces"

auth_command:
  command: |
    set -eu -o pipefail

db_pull_command:
  command: |
    # set -x # You can enable bash debugging output by uncommenting
    set -eu -o pipefail
    echo ${test}

files_pull_command:
  command: |
    # set -x   # You can enable bash debugging output by uncommenting
    set -eu -o pipefail
    echo ${test}
  service: web
```

Run with `ddev pull test -y --skip-import`

Result:

```bash
Authenticating... 
Obtaining database... 
variable
Skipping database import. 
Obtaining files... 
variable
Skipping files import. 
Pull succeeded. 
```

**Expected behavior**

The complete string should be available in the bash commands

```bash
Authenticating... 
Obtaining database... 
variable with spaces
Skipping database import. 
Obtaining files... 
variable with spaces
Skipping files import. 
Pull succeeded. 
```

**Version and configuration information (please complete the following information):**

- Host macOS Monterey 12.1 Apple M1
- Docker version 20.10.11, build dea9396
- ddev version v1.18.2

**Additional context**
https://discord.com/channels/664580571770388500/912420298488447026/928257058099302421
