### ISSUE TITLE
Add nodejs 20; Make nodejs 18 default in the ddev-webserver image

### ISSUE THREAD

**Issue by rodrigoaguilera** [ddev/ddev#4674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I know I can change the nodejs version in the configuration but I also use the same image in gitlab CI and is more complicated to change the nodejs version there. I need the fetch API to be available in nodejs

### Describe your solution

Update to v18 of nodejs as default. Nodejs 18 was released on 2022-04-19 and it is LTS. Even the variable in the ddev-php-base dockerfile is called NODE_LTS

### Additional context

Is there a policy for ddev as to when to change the default nodejs version?

**Comment by rfay** [comment]
It looks to me like we should add v20 and lose v14 probably in v1.22.0, and make v18 the default. https://nodejs.dev/en/about/releases/

I'd love to hear how you're using the ddev-webserver image in gitlab CI, and perhaps add a bit to https://ddev.readthedocs.io/en/latest/users/topics/remote-docker/#continuous-integration-ci about what you're doing?

**Comment by rfay** [comment]
Related:
* https://github.com/drud/ddev/issues/4250

It is awkward that we have two completely different ways to manage nodejs versions.

**Comment by rodrigoaguilera** [comment]
I'm not sure my case is an interesting example of how to use the image for CI.
Since developers use ddev for running nightwatch test I figured that it makes sense to use the same image in CI but probably I can just use an image that has `yarn` installed. I just want the dependencies to match versions.
Here is the job from the gitlab-ci that I use.
```
testing:nightwatch:test:
  image: drud/ddev-webserver:v1.21.3
  stage: e2e-tests
  services:
    - name: drupalci/chromedriver:dev
      alias: chromedriver
  script:
    - cat docroot/core/.env.example templates/.env.testing.test > docroot/core/.env
    - yarn --cwd docroot/core install
    - yarn --cwd docroot/core test:nightwatch --tag custom
```

I don't think it makes much sense to support nvm and the apt repos to swap nodejs versions. I think it is much simpler to use the apt repos in a containerized environment. I also noticed that nvm is not included in the image but is installed at runtime so there is a room for simplification.
