### ISSUE TITLE
Add pre/post share hooks

### ISSUE THREAD

**Issue by Biont** [ddev/ddev#4962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

WordPress installations store their host URL in the database in multiple places. Using `ngrok` with WordPress usually requires a `wp search-replace` CLI call for anything but the most basic usage scenarios. This is a little cumbersome to work around, so it would be great if you could consider this change.

### Describe your solution

`ddev share` should be among the [supported tasks](https://ddev.readthedocs.io/en/latest/users/configuration/hooks/#supported-tasks) for hooks.

Then you could do something like this:

```yaml
hooks:
  pre-share:
    - exec: wp search-replace $WP_URL $DDEV_SHARE_URL --all-tables --precise --recurse-objects
  post-share:
    - exec: wp search-replace $DDEV_SHARE_URL $WP_URL --all-tables --precise --recurse-objects
```

This assumes some environment variables that don't exist and are simply assumed for brevity. However, if you could actually export some `DDEV_SHARE_URL` to make it easily accessiblefor external scripting, that would be very much appreciated and obviously help a lot with pulling off the hook-based solution in a concise fashion.

Having this kind of extra setup wrapped in pre/post hooks seems like a very sensible thing to me - and would fit nicely with the existing API

### Describe alternatives

We currently use a wrapper script that

1. Runs `ddev share`
2. Grabs the ngrok URL from `localhost:4040/api/tunnels`
3. Runs `ddev exec wp search-replace`
4. Traps the script and restores the original URL when sharing is stopped.

It works, but it's an inelegant merge between host/container functionality and also is not portable across OSes.
