### ISSUE TITLE
Possible mutagen failure to sync on snapshot restore or post-start composer install

### ISSUE THREAD

**Issue by rfay** [ddev/ddev#5089]
There may be a situation reported by @mglaman in [Discord](https://discord.com/channels/664580571770388500/1125076127661166674/1126320464512421969) where `ddev snapshot restore` doesn't get mutagen properly synced. 

In his situation, he was using mutagen on linux in Github CI with post-start hooks that did a composer install.

They ran successfully on ddev start, but then failed on ddev snapshot restore.

```
hooks:
  post-start:
  - exec: chmod 775 web/sites/default
  - exec: composer install --prefer-dist --no-progress --no-interaction --apcu-autoloader
  - exec: composer dumpautoload -o
  - exec: vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer,vendor/slevomat/coding-standard,vendor/pheromone/phpcs-security-audit
  - exec: npm install
  - exec: npm install -g sass
  - exec: cd web/themes/custom/THEME && npm install
```

@hanoii reported a similar situation in private discord, apparently just on `ddev start` with a composer hook. But in this case it was fixed with `ddev restart`

```
Starting catalyze... 
mutagen sync catalyze exists but unable to get label:  
 Network ddev-catalyze_default  Created 
 Container ddev-catalyze-db  Created 
 Container ddev-catalyze-web  Created 
 Container ddev-catalyze-db  Started 
 Container ddev-catalyze-web  Started 
Starting mutagen sync process... This can take some time. 
Mutagen sync flush completed in 1s.
For details on sync status 'ddev mutagen st catalyze -l' 
 Container ddev-router  Running 
Composer could not find a composer.json file in /var/www/html
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
Task failed: Composer command '[install]' in web container: composer command failed: exit status 1 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
bash: /var/www/html/.ddev/platformsh-lite-addon-post-start.sh: No such file or directory
Task failed: Exec command 'bash /var/www/html/.ddev/platformsh-lite-addon-post-start.sh' in container/service 'web': exit status 127 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
bash: line 1: cd: web/themes/custom/catalyze_tw: No such file or directory
Task failed: Exec command 'cd web/themes/custom/catalyze_tw && yarn install && npx mix --production' in container/service 'web': exit status 1 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
bash: /var/www/html/.ddev/platformsh-lite-addon-post-start.sh: No such file or directory
Task failed: Exec command 'bash /var/www/html/.ddev/platformsh-lite-addon-post-start.sh' in container/service 'web': exit status 127 
A task failure does not mean that ddev failed, but your hook configuration has a command that failed. 
```

**Comment by rfay** [comment]
Ideas:
- [ ] `ddev restart` should check for upgrade and request poweroff
- [ ] app.Start() should, if there's a composer.json in composer_root, look for one in container, and warn if not. Debugging output.

**Comment by hanoii** [comment]
As discussed with Ray on zoom, here's some snippet of a config.yaml file of a project that failed due to a file not found on the web extra daemon :

```yaml
web_extra_daemons:
  - name: "pm2"
    command: "pm2 start --no-daemon .ddev/ecosystem.config.js"
    directory: /var/www/html
```
