### ISSUE TITLE
Select npm version in config.yaml 

### ISSUE THREAD

**Issue by DanielRuf** [ddev/ddev#5141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

There are valid reasons, why you may need a different npm version than the one that is shipped with the installed Nodejs version.

Especially if different lockfile versions are used, the correct npm version is relevant.

### Describe your solution

Implement `npm_version` comparable to `nodejs_version`.

### Describe alternatives

Document post-start hook example:

```yaml
hooks:
  post-start:
    - exec: "npm i -g npm@6"
```

### Additional context

https://github.com/ddev/ddev/issues/2651#issuecomment-1636514338

https://github.com/ddev/ddev/issues/2651

**Comment by stasadev** [comment]
This hook installs `npm` every time you start the project:

```yaml
hooks:
  post-start:
    - exec: "npm i -g npm@6"
```

This is because `/usr/bin/npm` is reverted to its original state after stopping the project.

A better alternative is to use `nvm` to override `node` and install `npm` only once:

```yaml
hooks:
  post-start:
    - exec: "[[ "$(nvm current)" != "system" ]] || (nvm i 14 && npm i -g npm@6)"
```
