### ISSUE TITLE
Distribute DDEV Windows using winget repository

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#5224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Recently, I had an issue with chocolately and learnt about Winget.

[Winget](https://github.com/microsoft/winget-cli) is Microsoft's official CLI package manager. 
It is installed by default on Win10+ OSs.

### Describe your solution

Add DDEV to winget repository.

I followed [this guide](https://learn.microsoft.com/en-gb/training/modules/explore-windows-package-manager-tool/6-contribute-to-repository), and submitted a [request ](https://github.com/microsoft/winget-pkgs/pull/114945),  with the following details:

```yaml
PackageIdentifier: ddev.ddev
PackageVersion: 1.22
PackageLocale: en-US
Publisher: DDEV
PackageName: ddev
License: Apache-2.0
ShortDescription: DDEV is an open source tool for running local web development environments for PHP, Python and Node.js, ready in minutes.
ManifestType: defaultLocale
ManifestVersion: 1.4.0
```

### Describe alternatives

Winget is for modern Windows OS (10+), the same as listed on DDEV GitHub page.
This installation pathway could replace the need to install `chocolately` which may lower the installation barrier for some people.

### Additional context

I know you have talked about dropping traditional windows support (non WSL), 
I'm not sure if this is still under consideration.

I'll close this and the upstream request if you feel it would not benefit the DDEV project.

Not sure if you would prefer to submit the request from an "official" DDEV account.

TODO: 
- [x] [Complete application process](https://github.com/microsoft/winget-pkgs/pull/114945)
- [ ] Update docs with new pathway
