### ISSUE TITLE
Failed to run custom DDEV image

### ISSUE THREAD

**Issue by LorenzoAlu** [ddev/ddev#5225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
Failed to start vw-private-rental-simulator: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-rental-simulator docker-compose -f /Users/lorenzo.alu/Desktop/wa/rental-simulator/.ddev/.ddev-docker-compose-full.yaml up -d', action='[up -d]', err='exit status 1', stdout='', stderr=' Container ddev-rental-simulator-web  Creating
 Container ddev-rental-simulator-sqlserver  Created
 Container ddev-rental-simulator-web  Created
 Container ddev-rental-simulator-web  Starting
 Container ddev-rental-simulator-sqlserver  Starting
 Container ddev-rental-simulator-sqlserver  Started
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/pre-start.sh": stat /pre-start.sh: no such file or directory: unknown' 
```
</details>         

### Expected Behavior

Out of necessity I am using an custom image where I install `sqlServer` db inside DDEV container. 
The image on which it is mounted takes the base version `1.19.0`.

After the last update I can no longer start the DDEV using this custom image.

I tried updating the image with the latest version of DDEV available from the docker hub (`1.21.5`). I can mount it, run it and push it to the docker hub, but when I try to start the project I get the above error.

Where am I going wrong? Is it an error on my part due to forgetting something or is it a bug?

### Actual Behavior

Currently, I can no longer start projects that have that image.

### Steps To Reproduce

This is my DDEV `config`:
```yaml
type: php
docroot: public
php_version: "7.2"
webserver_type: apache-fpm
webimage: xxx/ddev-webserver:1.21.5
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
  - rental-simulator
  - leasing-simulator
additional_fqdns: [ ]
override_config: true
hooks:
  post-start:
    - exec: nvm install && nvm use
omit_containers: [ db ]
host_db_port: "52789"
webimage_extra_packages: [ wkhtmltopdf ]
use_dns_when_possible: true
composer_version: "2"
web_environment:
  - PHP_IDE_CONFIG=serverName=${DDEV_PROJECT}
nodejs_version: "14"
```

The image, on the other hand, is created in the following way: 

DockerFile

```dockerFile
FROM drud/ddev-webserver:v1.21.5

ENV PHP_VERSIONS_SQLSERVER="php7.2 php7.4 php8.0 php8.1"
ENV PHP_VERSIONS_NUMBER_SQLSERVER="7.2 7.4 8.0 8.1"

RUN apt-get -qq update && \
    apt-get -qq install --no-install-recommends --no-install-suggests -y \
    	apt-utils \
    	php-pear \
    	g++ \
    	build-essential \
        xdg-utils

RUN for v in $PHP_VERSIONS_SQLSERVER; do \
    apt-get -qq install --no-install-recommends --no-install-suggests -y --option=Dpkg::Options::=--force-confdef \
    $v-dev; \
done

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc \
    source ~/.bashrc

RUN apt-get -qq update && \
    ACCEPT_EULA=Y apt-get install -y \
    msodbcsql18 \
    mssql-tools18 \
    unixodbc-dev

ADD sqlserver.sh /
RUN chmod ugo+x /sqlserver.sh
RUN mkdir /temp
RUN /sqlserver.sh
RUN rm -rf /temp

```

sqlServer.sh

```sh
#!/usr/bin/env bash
 for v in $PHP_VERSIONS_NUMBER_SQLSERVER; do
   echo "INSTALL $v"
   pecl -d php_suffix=$v install -f sqlsrv-5.11.0
   pecl -d php_suffix=$v install -f pdo_sqlsrv-5.11.0
   cmdphp="/usr/bin/php-config$v --extension-dir"
   phpdir=$(eval $cmdphp)
   echo extension=sqlsrv.so >/etc/php/$v/mods-available/sqlsrv.ini
   echo extension=pdo_sqlsrv.so >/etc/php/$v/mods-available/pdo_sqlsrv.ini
   echo "COPY FOR $v FROM $phpdir TO temp"
   cp $phpdir/sqlsrv.so /temp/sqlsrv-$v.so
   cp $phpdir/pdo_sqlsrv.so /temp/pdo_sqlsrv-$v.so
   echo "END COPY FOR $v"
 done
 for v in $PHP_VERSIONS_NUMBER_SQLSERVER; do
   cmdphp="/usr/bin/php-config$v --extension-dir"
   phpdir=$(eval $cmdphp)
   echo "COPY FOR $v FROM temp TO $phpdir"
   cp /temp/sqlsrv-$v.so $phpdir/sqlsrv.so
   cp /temp/pdo_sqlsrv-$v.so $phpdir/pdo_sqlsrv.so
   echo "END COPY FOR $v FROM tmp"
   phpenmod -v $v sqlsrv
   phpenmod -v $v pdo_sqlsrv
 done

```

### Anything else?

I remain available to share more code and solve the problem.
I've been banging my head on it for days and I'm going crazy :D
