### ISSUE TITLE
"Unable to gather manifests" when installing add-on with dependencies from local directory

### ISSUE THREAD

**Issue by JanoPL** [ddev/ddev#5254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
.ddev/addon-metadata: no such file or directory
```
</details>         

### Expected Behavior

to install addon from directory with command ```ddev get <local dir>```

when the addon install.yaml has configured option dependencies

whitout dependecies key in yaml file is working fine.

example for adminer addon install.yaml
```yaml 
name: adminer

# list of files and directories listed that are copied into project .ddev directory
project_files:
- docker-compose.adminer.yaml
- adminer

dependencies:
  - db

global_files:
- commands/host/launcha
```

![image](https://github.com/ddev/ddev/assets/37768741/353a24e6-898c-41c0-87fe-19c41e572245)

### Actual Behavior

it can't create addon-metadata directory when addon is installed locally for example: ddev get /home/user/ddev-adminer/
Unable to gather manifests: open /home/user/test-app/.ddev/addon-metadata: no such file or directory

![image](https://github.com/ddev/ddev/assets/37768741/ab37914e-1365-4890-bddb-dc4bb778e7e4)

### Steps To Reproduce

1. generate new config or using existing for ddev
2. check if addon-metada not exist in .ddev directory
3. clone addon repo to local directory
4. execute ddev get addon

commands: 
1. ```ddev config```
2. ```[ ! -d "/.ddev/addon-metadata/" ] && echo "Directory /.ddev/addon-metadata/ DOES NOT exists."```
3. ```git clone git@github.com:ddev/ddev-adminer.git```
4. ```ddev get <local path>/ddev-adminer```
