### ISSUE TITLE
Create additional databases without importing data

### ISSUE THREAD

**Issue by nickperkins** [ddev/ddev#5406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

As a developer of a CiviCRM project using Drupal as the CMS
I want to be able to create a database without importing a database dump
So that when CiviCRM is installed, it can setup the second database via its installation process

### Describe your solution

Add a `ddev create-db` command that would allow the creation of additional empty databases. 

`ddev create-db --database civicrm` would create a secondary database called `civicrm`.

### Describe alternatives

Alternative method at the moment is to run the sql commands manually, or perhaps create some sort of empty import file.

### Additional context

Just an idea that would be a nice QoL fix for those who need it.

**Comment by rfay** [comment]
This is already easy. You have full control. For example, see https://stackoverflow.com/a/51253896/215713

```
ddev mysql -uroot -proot -hdb -e "CREATE DATABASE IF NOT EXISTS another_db; GRANT ALL ON another_db.* TO 'db'@'%';"
```

You can do it with a post-start hook, you can do it with `ddev mysql`, You can do it inside the webcontainer with `mysql`, you can do it inside the db container with mysql.

You could even use import-db with an empty file :)

**Comment by galliroberto** [comment]
How to do it for postgres?

**Comment by tyler36** [comment]
@galliroberto 

- Use `ddev psql` to open the Postgres terminal.

- Use `ddev psql -c` to run a SQL command. 

```
ddev psql -c "CREATE DATABASE monkey;"
```

**Comment by galliroberto** [comment]
finally i did it
postgres has only user db/db

```
hooks:
  post-start:
    - exec: PGPASSWORD=db psql -h db -U db -c "CREATE DATABASE monitoring;"
      service: db
```

**Comment by stasadev** [comment]
@galliroberto,

Your hook will fail on second `ddev restart`, because database will exist.
(And PostgreSQL doesn't have `CREATE DATABASE IF NOT EXISTS`.)

Use this instead:

```yaml
hooks:
    post-start:
        - exec: db_name=db2; psql -lqt | cut -d \| -f 1 | grep -qw $db_name || psql -c "CREATE DATABASE $db_name"
```
