### ISSUE TITLE
Shopware: Using watcher gives either 404 page not found or Bad Gateway error

### ISSUE THREAD

**Issue by zaifastafa** [ddev/ddev#5437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

Hi, I am using the following `docker-compose.watcher.yaml` file as per this [article](https://susi.dev/ddev-shopware-6/) 

```
# .ddev/docker-compose.watcher.yaml
version: "3.6"

services:
    web:
        expose:
            # Storefront Hot Proxy Ports
            - 9997
            - 9998
            - 9999
        environment:
            # Shopware Administration Watch Host
            - HOST=0.0.0.0
            # Shopware Administration Watch Port
            - PORT=9997
            # Expose APP_URL to administration watcher
            - APP_URL=http://${DDEV_SITENAME}.ddev.site
            - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,9999:9999,9998:9998,9997:9997
            - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,8899:9999,8888:9998,8887:9997

```

But when I run the watcher and go to the port, I get 404 page not found or Bad gateway. 

### Expected Behavior

I can use the watcher on the designated port

### Actual Behavior

Getting 404 page not found error.

**Comment by rfay** [comment]
Hi @zaifastafa - 
* Are you starting the watcher? You have to start the process, right? `ddev exec bin/watch-storefront.sh`
* Note that `version: 3.6` is obsolete these days and that line can be removed.
* I think this can be improved quite a lot with more modern use of DDEV config, like `web_extra_exposed_ports` and perhaps `web_extra_daemons`. 

I hope you'll keep working on it and create a DDEV add-on to implement this, since it's an important contribution by @susannemoog , but needs to be updated.

You're definitely using Shopware 6?

**Comment by rfay** [comment]
No response from @zaifastafa , and this probably isn't the right place for the issue anyway, but happy to continue the conversation here or in Discord, https://discord.gg/hCZFfAMc5k - closing this for now.

**Comment by ChristopherDosin** [comment]
@rfay I am having the same issue.
The hot-proxy is running at port `9998` .

So i've added the following to my `config.yml`

```
web_extra_exposed_ports:
    - name: hot-proxy
      container_port: 9998
      http_port: 8888
      https_port: 9998
```

However: Within the console I am getting a 
```
Rejecting request "GET 127.0.0.1/" on proxy server for "127.0.0.1:9998"
```
when i want to access `https://sitename.ddev.site:9998` and a `Bad Gateway` within the browser.
