### ISSUE TITLE
Have a way to make an additional hostname a subdomain without re-typing the project name

### ISSUE THREAD

**Issue by hanoii** [ddev/ddev#5486]
I use `additional_hostnames` a lot, and everytime I set up things as subdomains of the project name.

i.e.
```yaml
name: example
additional_hostnames:
    - 'something.example'
    - 'else.example'
    - '*.example'
```

I would love to be able to avoid the `example` mostly so that I can bundle some of this on an add-on where I don't know the project name.

I am not sure what's best here. I thought of using a simple go template approach with a defined set of variables, like `{{ . ProjectName }}` or something like that. Another option is to allow for some custom STRING, like `$DDEV_PROJECT`, but I think using something that looks like an env var is confusing.
