### ISSUE TITLE
Starting Mutagen sync process... This can take some time - 10 minutes+

### ISSUE THREAD

**Issue by Coysh** [ddev/ddev#5539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
Not running due to mutagen still loading up
```
</details>         

### Expected Behavior

`ddev start` to boot up the environment within a few mnutes

### Actual Behavior

`ddev start` takes over 10 minutes to start the mutagen process

### Steps To Reproduce

1. Run `ddev start`
2. Wait forever

### Anything else?

This is my `config.yaml` 

```
name: craftcms-site
type: craftcms
docroot: cms/web
php_version: "8.1"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "18"
upload_dirs:
    - files
    - node_modules
    - imager
    - cpresources
    - storage
    - uploads
 ```
 
 I occassionally get the following error but not consistent:
```
Failed to start craftcms-site: failed to create Mutagen sync session 'compliance-ai'. You may be able to resolve this problem using 'ddev mutagen reset' (err=muForcing synchronization cycle for session sync_mFQew2hy1JVlwdU2IQBwEAUV8NrgDuaz1
Error: unable to flush session: synchronization failed while waiting for flush response
, err=exit status 1) 
```
