### ISSUE TITLE
Log stderr to a file accessible by "ddev logs"

### ISSUE THREAD

**Issue by trsteel88** [ddev/ddev#5794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

A Symfony application can create massive log files which result in mutagen sync'ing taking a very long time.

The recommendation by Symfony is to output monolog errors to "php://stderr". See https://symfony.com/blog/logging-in-symfony-and-the-cloud

When you're in a "dev" environment in Symfony it logs at a "DEBUG" level which means that a console command can be flooded with DEBUG "errors" even though they aren't critical errors.

For example, Doctrine queries are logged. If you're performing database queries it is easy to get lost in the output.

### Describe your solution

Is there a way that stderr could be logged to a ddev log rather than being output to the terminal? Only stdout should show in the terminal?

**Comment by trsteel88** [comment]
Here is an example config for logs errors to a file

```yaml
...
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
...
```

The above results in mutagen sync delays when the log file grows.

Here is the config to log to stderr

```yaml
...

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                level: debug
...
```

Alternatively, we could log to a file outside the project. e.g:

```yaml
...
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: '/var/log/app.log'
                level: debug
```

I'm not sure if there would be any consequences to this other than the log would be reset when the container stops (but I don't see this as a problem as they are temp logs).

**Comment by trsteel88** [comment]
Digging into logs further I noticed that `ddev logs` looks at /var/tmp/logpipe.

The following will log it to the web logs:

```yaml
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: /var/tmp/logpipe
                level: debug
```
