### ISSUE TITLE
ADD ability to set MySQL/MariaDB/PostgreSQL Global Variables in config.yaml #sql_mode

### ISSUE THREAD

**Issue by allanlaal** [ddev/ddev#5908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I need to set custom sql_mode for a project
I clone a default dir to ticket dir and run separate ddev instances for each

### Describe your solution

Add config.yaml variable database.environment, which is a list like web_environment, where one can override any global variables

example:

```
...
additional_fqdns: []
database:
    type: mariadb
    version: 10.6
    environment:
        - "sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER"
        - "max_connections=1337"
use_dns_when_possible: true
...
```

### Describe alternatives

manual work
