### ISSUE TITLE
Can't create snapshot with same name if there's existing one with different database engine

### ISSUE THREAD

**Issue by hkirsman** [ddev/ddev#6045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
I don't think for the current issue this is not needed but I'll send it if you really need it.
```
</details>         

### Expected Behavior

I have snapshot main-mariadb_10.4.gz . When I delete my local env, switch from mariadb to mysql in config.yaml and try to create snapshot, it should be able to do so because there's no main-mysql_10.4.gz snapshot yet.

### Actual Behavior

I'm greeting with incorrect error:
Failed to snapshot example.com: snapshot main-mysql_8.0.gz already exists, please use another snapshot name or clean up snapshots with `ddev snapshot --cleanup`

That file does not exist. So I guess it only checks for the snapshot name itself, then generates the error based on current setup.

### Steps To Reproduce

1. Start with mariadb configuration

```
name: example.com
type: drupal10
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.4"
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
web_environment: []
nodejs_version: "16"

```

2. Create snapshot 
`ddev snapshot --name main`

3. Export your database
`ddev export-db --gzip=false --file=main.sql` (without gzip because maybe it's a bit faster :) )

4. Destroy the old env
ddev delete --omit-snapshot --yes 

5. Switch to the new mysql db in config.yaml:
```
database:
    type: mysql
    version: "8.0"
```

6. Init the new env:
`ddev start`

7. Import DB dump.
ddev import-db --file=mysql8-tmp.sql 

8. Try to create snapshot again:
`ddev snapshot --name main`
