### ISSUE TITLE
Feature request: Lifecycle hooks

### ISSUE THREAD

**Issue by adrianrudnik** [ddev/ddev#6157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Jetbrains plugin [not working](https://github.com/php-perfect/ddev-intellij-plugin/issues/307) for some time now. User @shochdoerfer [suggested](https://github.com/php-perfect/ddev-intellij-plugin/issues/307#issuecomment-2092437859) a passive approach not involving the IDE at all.

What if people could develop their own solutions to their problems, by hooking into the DDEV lifecycle, like only first-start / start / stop / delete? Does not matter if I need to do additional configuration, do an rsync, if a user can hide it in an executable, DDEV can stay clean.

For this problem, I could write a simple Go binary to take DDEV configuration values given to me and rebuild/reconfigure the `.idea/` folder, if present, with the correct details, like new db connection details.

### Describe your solution

Define additional nodes within `.ddev/config.yaml` like

```yaml
hook:
  first-start:
   # option with all parameters
    - { name: full variant, os: linux, path: ./path-relative-to-dot-ddev/firstrun.sh }
   # option without name
    - { os: windows, path: ./path-relative-to-dot-ddev/firstrun.bat }
  start:
    # shortest variant, will execute on all OSes
    - ./start-vpn.sh
    - ./configure-ide.sh
  stop: 
    - ./stop-vpn.sh
  delete:
    - ./delete-vcloud-instance.sh
    - ./stop-vpn.sh
```

- `os` will compare against `GOOS`, and only execute when matching.
- `name` can be defined by or omitted, not really important.
- `path` will be relative to `.ddev/`

Every hook will do a OS execute on the given paths, injecting data available within `ddev describe`  as ENV variables to use within the script, within the order given. Failure to execute a hooked script will warn about it, but not further influence the DDEV flow.

### Describe alternatives

I have no alternatives.

### Additional context

I've search through other issues which like #5557 and #5448, which were on per-command and not that helpful. This is not on per command, this is about the container lifecycle which otherwise would need additional extra commands.
