### ISSUE TITLE
Make it possible to activate more than 20 projects at a time.

### ISSUE THREAD

**Issue by steveoriol** [ddev/ddev#6308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I need to have more than 20 projects running on the same server.
and it seems to me that this isn't possible because ddev can't find an available IP to start the site and the DB...
Here's the error after a "ddev strart" on a 21st project:

```shell
❯ ddev start project21
Starting project21...
Building project images...
.Project images built in 1s.
 Network ddev-project21_default  Error
failed to create network ddev-artiop_default: Error response from daemon: could not find an available, non -overlapping IPv4 address pool among the defaults to assign to the network
Failed to start project21: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-project21 docker-compose -f /home /steve/ddev-sites/project21/.ddev/.ddev-docker-compose-full.yaml up -d', action='[up -d]', err='exit status 1 ', stdout='', stderr=' Network ddev-artiop_default  Creating
Network ddev-artiop_default  Error
failed to create network ddev-artiop_default: Error response from daemon: could not find an available, non -overlapping IPv4 address pool among the defaults to assign to the network'  
``` 

What frustrates me is that out of the 65534 IPs in the 192.168.0.1/16 range, only 20 projects can be started.

### Describe your solution

We could imagine that the IP ranges reserved for each project could be smaller,
like if the "subnet mask" is changed from 20 to 21 or 22 or 23 or even 24,
we'd go from 65534 IPs per project to ;

- 2046 for a subnet of 21
- 1022 fora subnet of 22
- 510 fora subnet of 23 
- and 254 fora subnet of 24. 

Which is still quite a lot for Nb. of IPs for a dev site ;-)

### Describe alternatives

we could also imagine the "subnet mask" being a global parameter and.or per project to be modified in the .yml file

**Comment by stasadev** [comment]
Hi @steveoriol,

It seems to be related to:

- #5885

**Comment by rfay** [comment]
As @stasadev says, This is a problem with your Docker configuration, not DDEV I don't think.

But you didn't provide the requested `ddev debug test` so we have no insight into your situation.

**Comment by steveoriol** [comment]
Thanks for your quick answers, I'll have a look at : 
https://straz.to/2021-09-08-docker-address-pools/
And I'll report back HERE.

**Comment by rfay** [comment]
Thanks @steveoriol - I host small sites with it as well. And I just figured out how to do Let's Encrypt with the traefik router. Are you using Let's Encrypt?

Closing as duplicate of 
* https://github.com/ddev/ddev/pull/5885

**Comment by steveoriol** [comment]
@rfay,
Yes, I use Let's Encrypt, but I don't only have websites via DDEV on the server.
I also have other services like redmine, nextcloud, n8n, etc... in docker containers.
So, my strategy is to have a "traefik" docker container (Master), that manages all the redirects to the services and the DDEV sites, and also takes care of adding SSL with Let's Encrypt.

In this way, the DDEV's "traefik" is not exposed directly on the Internet, it remains local, and I just modifed the ports inside "~/.ddev/global_config.yaml" file with :
```yml
router_http_port: "8080"
router_https_port: "8443"
``` 
Just so as not to interfere with the "MASTER traefik".

I add the DDEV site network to the "MASTER traefik" network via a hook in the "SITE/.ddev/config.yaml" site configuration file:
```yml
hooks:
  post-start:
     - exec-host: "docker network connect traefik-proxy ddev-SITE-web"
``` 
Here's an example of how to configure a site on the MASTER traefik in dynamic mode,
file " ~/DOCKER/traefik/dynamic/ddev-SITE.yml":
```yml
http:
  services:
    ddevSITE:
      loadBalancer:
        servers:
          - url: "http://ddev-SITE-web:80"
  routers:
    ddevSITE-secure:
      rule: "Host(`xxxxx.xxxxx.com`)"
      service: "ddevSITE"
      middlewares:
        - "SecureHeaders@file"
      tls:
        certResolver: letsencrypt
``` 
And it's working pretty well for me so far ;-)
