### ISSUE TITLE
Feature request: Map services/port to host names.

### ISSUE THREAD

**Issue by mortona42** [ddev/ddev#6487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

DDEV hosts services on different ports, with the http ports pointing at the web container.

I would prefer to have memorable urls for services like mailpit.SITE.ddev.site. I think I would need to configure this in the nginx settings (or maybe traefik router?). It would be great if this was a global setting in config.yaml or even enabled by default.

In addition, I am running vite in dev mode in the web container. I can define an extra exposed port to connect to it in the browser, but would like a way to add an additional hostname and assign it that port.

Lando has service hostnames set up by default, and an easy way to map new hostnames to a port on a service:

```
proxy:
  node:
    - node.SITE.lndo.site:3000

services:
  node:
    type: node:20
    ssl: true
    sslExpose: false
    port: 3000
    scanner: false
```

### Describe your solution

I think the lando solution is perfect and we should implement something similar.

### Describe alternatives

This may be doable with a bit of documentation, or a contrib plugin.

### Additional context

I am unsure if there is a reason NOT to provide hostnames for services.
