### ISSUE TITLE
Storefront watcher not working correctly in shopware 6.6

### ISSUE THREAD

**Issue by yanneckb** [ddev/ddev#6616]
### Expected Behavior

*PHP Version:* 8.2   | *Shopware Version:* 6.6.7.0  | *Affected area / extension:* Platform(Default) 

 ----

Hey guys,
I have a new shopware 6.6.7.0 project runnning with latest ddev but the storefront watcher is making some problems... the watcher should work correctly with all assets displayed and reacting to changes, when i start it in the ddev ssh via `bin/watch-storefront.sh`

### Actual Behavior

First i got a deprecated warning with puppeteer and a chromium install error. I fixed it by adding "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true" to the config.watcher.yaml:

```
### ./.ddev/config.watcher.yaml ###

web_extra_exposed_ports:
  - name: storefront-watcher
    container_port: 9998
    http_port: 9998
    https_port: 9998 ## also tried 9999
  - name: admin-watcher
    container_port: 8888
    http_port: 8888
    https_port: 8889

web_environment:
  - HOST=0.0.0.0
  - PORT=9998
  - APP_URL=${DDEV_PRIMARY_URL}
  - ESLINT_DISABLE=true
  - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
``` 

The watcher starts now with this error:
```
Unable to open browser! Details:
Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'https://richartz-shop.ddev.site:9998/' ]
}
```

but this is not my main problem. The REAL problem is, that the watcher is running on https://my-shop.ddev.site:9998/, but all the images are loaded via http://my-shop.ddev.site:9998/. When i go to https://my-shop.ddev.site/ all images are loaded via https again. Only the watcher is making problems...
Also tried adding this to public/.htaccess:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>
```

Does anybody have an idea? When i start the project with devenv, everything is working fine... only with ddev i have problems

Greetings!
Yanneck

### Steps To Reproduce

Set up new shopware 6.6 project with ddev and add storefront watcher configuration

**Comment by yanneckb** [comment]
Hey @rfay, I have updated ddev to v1.23.4 but when I do ddev --version I get`ddev version v1.23.1`.
I removed the ddev debug test because there was company data inside. But I found the error
 
```
3.162 W: GPG error: http://nginx.org/packages/debian bookworm InRelease: The following signatures were invalid: EXPKEYSIG ABF5BD827BD9BF62 nginx signing key <signing-key@nginx.com>
3.162 E: The repository 'http://nginx.org/packages/debian bookworm InRelease' is not signed.
```

Maybe it has something to do with my .ddev/config.yaml configuration
`webserver_type: nginx-fpm`

**Comment by yanneckb** [comment]
@rfay okay this helped updating my ddev version correctly but it doesnt fix my problem with the watcher that the images are not loaded correctly

**Comment by rfay** [comment]
Can you please start over, provide the output of `ddev debug test` as a gist at gist.github.com and give a link, and update the original post to say exactly what's happening?

I don't know why you need chromium for the storefront watcher, but if you need it, I'm sure you need it. 

Where did you get the recipe you're using for the watcher? Has it worked for you before? 

Note that if you're not using the `apache-fpm` webserver_type then changing htaccess does nothing.

You can't do an `xdg-open` from inside the web container (if that's what you're doing) because there is no browser. Or maybe it's supposed to have the headless chrome and you've removed it. But I don't know that xdg-open could work with headless chrome.

**Comment by stasadev** [comment]
```yaml
web_extra_exposed_ports:
  - name: storefront-watcher
    container_port: 9998
    http_port: 9998
    https_port: 9998 ## also tried 9999
```

> The REAL problem is, that the watcher is running on https://my-shop.ddev.site:9998/, but all the images are loaded via http://my-shop.ddev.site:9998/. When i go to https://my-shop.ddev.site/ all images are loaded via https again. Only the watcher is making problems...

---

I think you want to use this configuration instead with `http_port: 9999` (I usually add +1 to `http_port`):

```yaml
web_extra_exposed_ports:
  - name: storefront-watcher
    container_port: 9998
    http_port: 9999
    https_port: 9998
```

It should work with `https://my-shop.ddev.site:9998/`

Note that `http_port` and `https_port` cannot be the same.

**Comment by yanneckb** [comment]
@stasadev Hey, I tried it but sadly it doesn't work either with different ports...

**Comment by stasadev** [comment]
> Steps To Reproduce
> Set up new shopware 6.6 project with ddev and add storefront watcher configuration

@yanneckb,

These steps are not enough for me, because I'm not a Shopware user.
Please create a test repository on GitHub for this so we can try it out and tell if there's anything wrong with this setup.
Add all the necessary steps in README.md there.

Thank you.

**Comment by yanneckb** [comment]
@stasadev I created a new shopware 6.6.6.7 project and added my ddev configuration and setup guide in the readme https://github.com/yanneckb/ddev-shopware6-6-test
thanks for your help! Maybe you find something...

**Comment by rfay** [comment]
Can you say why you're using xdg-utils there? It can only work on a system with a browser, and there is no browser inside the web container.... (If you do want to install a package, the easy way is with `webimage_extra_packages`, see https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/#adding-extra-debian-packages-with-webimage_extra_packages-and-dbimage_extra_packages )

**Comment by yanneckb** [comment]
@rfay it fixed the xdg error for a short time, but now it reappears. Even with `webimage_extra_packages: [xdg-utils]` in the config

**Comment by stasadev** [comment]
Thank you @yanneckb,

I think this is the same as:

- https://github.com/ddev/ddev/issues/5437#issuecomment-1905755834

Try this out, it should move things forward (it shows Shopware Domain Mapping Misconfiguration Help for me, but at least this is something):

```
ddev config --web-environment-add 'ENV_FILE=${DDEV_COMPOSER_ROOT}/.env.local'
ddev ssh
bin/watch-storefront.sh
```

**Comment by yanneckb** [comment]
I adjusted the configuration to a docker-compose.watcher.yaml and adding the ENV_FILE environment and the additional hostnames:

```
# .ddev/docker-compose.watcher.yaml
services:
  web:
    expose:
      - 9997
      - 9998
      - 9999
    environment:
      - ESLINT_DISABLE=true
      - HOST=0.0.0.0
      - PORT=9997
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,8899:9999,8888:9998,8887:9997
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,9999:9999,9998:9998,9997:9997
````

```
web_environment:
  - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
  - ENV_FILE=${DDEV_COMPOSER_ROOT}/.env.local
additional_hostnames: ["my-shop.ddev.site", "*.ddev.site.ddev.site", "my-shop.ddev.site.ddev.site"]
```

```
name: my-shop
type: shopware6
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
performance_mode: none
use_dns_when_possible: true
composer_version: "2"
corepack_enable: false
```

now the watcher works but the assets are still loaded via http instead of https... okay for now but still not perfect :D
