### ISSUE TITLE
Make `ports` in `docker-compose.*.yaml` respect `bind-all-interfaces=false` project option

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#6943]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

Some add-ons like https://github.com/ddev/ddev-sqlsrv/blob/main/docker-compose.sqlsrv.yaml#L19 use `ports` directly.

But it's exposed on `0.0.0.0`, instead of `127.0.0.1`, which is default in DDEV.

To reproduce:

```
mkdir ports-test && cd ports-test
ddev config --bind-all-interfaces=false
printf "services:\n  web:\n    ports:\n      - 12345:12345\n" > .ddev/docker-compose.web.yaml
ddev start
```

```yaml
services:
  web:
    ports:
      - 12345:12345
```

Look for `ports` configuration in `.ddev/.ddev-docker-compose-full.yaml`:

```yaml
ports:
    - host_ip: 127.0.0.1
        mode: ingress
        protocol: tcp
        target: 80
    - host_ip: 127.0.0.1
        mode: ingress
        protocol: tcp
        target: 443
    - mode: ingress
        protocol: tcp
        published: "12345"
        target: 12345
```

And check the ports, I did this on Linux:

```
$ sudo netstat -tulpn | grep LISTEN | grep docker-proxy
tcp        0      0 127.0.0.1:10999         0.0.0.0:*               LISTEN      157680/docker-proxy 
tcp        0      0 127.0.0.1:443           0.0.0.0:*               LISTEN      157656/docker-proxy 
tcp        0      0 127.0.0.1:32798         0.0.0.0:*               LISTEN      154264/docker-proxy 
tcp        0      0 127.0.0.1:32799         0.0.0.0:*               LISTEN      154302/docker-proxy 
tcp        0      0 127.0.0.1:32797         0.0.0.0:*               LISTEN      154256/docker-proxy 
tcp        0      0 127.0.0.1:80            0.0.0.0:*               LISTEN      157649/docker-proxy 
tcp        0      0 0.0.0.0:12345           0.0.0.0:*               LISTEN      154229/docker-proxy 
tcp        0      0 127.0.0.1:8026          0.0.0.0:*               LISTEN      157671/docker-proxy 
tcp        0      0 127.0.0.1:8025          0.0.0.0:*               LISTEN      157665/docker-proxy 
tcp6       0      0 :::12345                :::*                    LISTEN      154245/docker-proxy
```

Specifically:
```
tcp        0      0 0.0.0.0:12345           0.0.0.0:*               LISTEN      154229/docker-proxy 
tcp6       0      0 :::12345                :::*                    LISTEN      154245/docker-proxy
```

### Describe your solution

Make it respect `ddev config --bind-all-interfaces=false`

The fix can be applied to `ddevapp.fixupComposeYaml()` for each `services[][ports]`.

### Describe alternatives

Manually add `127.0.0.1`:

```yaml
services:
  web:
    ports:
      - 127.0.0.1:12345:12345
```
