### ISSUE TITLE
Add a command to delete a volume by name

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev#6961]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

From https://github.com/ddev/ddev-solr/pull/50/files#r1942518655:

Can we provide a simple ddev command that deletes a volume?
Maybe that would be a ddev feature request to delete the volume(s) that belong to a service.

```
docker volume rm ddev-$(ddev status -j | docker run -i --rm ddev/ddev-utilities jq -r '.raw.name')_solr
```

### Describe your solution

Add a new command under `ddev debug` to delete the volume by its name.

Volumes can also have a different name:

```yaml
volumes:
    database:
        external: true
        name: d11-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir
    solr:
        name: ddev-d11_solr
```

I think it would be good to make it work for both short `solr` and long `ddev-d11_solr` names.

### Additional context

Consider deleting a volume on `ddev add-on remove`, but I'm not sure if it's easy to detect which volume(s) belong to a specific service.
