### ISSUE TITLE
Add NuxtJS to docs quickstart

### ISSUE THREAD

**Issue by jonagoldman** [ddev/ddev#7029]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

I would love to see an example for a NuxtJS quickstart beside the currently available SvelteKit example in https://ddev.readthedocs.io/en/stable/users/quickstart/#nodejs

I'm trying to start a deamon to run NuxtJs on a `generic` project using `web_extra_daemons` like this:

### Describe your solution

```
name: godesk-nuxt
type: generic
docroot: public
webserver_type: generic
nodejs_version: "22.12"
timezone: UTC
web_extra_exposed_ports:
  - name: nuxt
    container_port: 3000
    http_port: 2999
    https_port: 3000
web_extra_daemons:
  - name: "nuxt-dev"
    command: "pnpm dev"
    directory: /var/www/html
```
