### ISSUE TITLE
Exposing node application on subdomain to port 80/443. Can this be achieved?

### ISSUE THREAD

**Issue by ayalon** [ddev/ddev#7190]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

Hi

Assuming we have the DDEV Site `example.ddev.site`
I know, that I can export a node application with an additional port. This works.
```
web_extra_exposed_ports:
  - name: "node-app"
    container_port: 3000
    http_port: 3000
    https_port: 3001
```

Assume I would prefer to expose my node app to port 80 / 443 but not on `example.ddev.site` (there we already have nginx.)

I would like to proxy `frontend.example.ddev.site` via 443 to 3000 in the webcontainer.

With lando this was quite easy and I'm pretty sure, traeffik can easily do that (no need for nginx in between) but I don't know how to achieve this.

Could you guide me here?

### Expected Behavior

I would like to proxy `frontend.example.ddev.site` via 80/443 to 3000 in the webcontainer while nginx occubpies `example.ddev.site` with 80/443

### Actual Behavior

Works as expected

**Comment by rfay** [comment]
You should be able to accomplish this with a `docker-compose.*.yaml` and your own overrides for VIRTUAL_HOST, see https://ddev.readthedocs.io/en/stable/users/extend/custom-compose-files/#conventions-for-defining-additional-services

But `web_extra_exposed_ports` won't do it for you. I don't know for sure that you can do it. But search docs for VIRTUAL_HOST and understand HTTP_EXPOSE and HTTPS_EXPOSE.

**Comment by stasadev** [comment]
Here is how to do it:

Assuming this config in the `.ddev/config.yaml` file:

```yaml
name: example
additional_hostnames:
    - frontend.example
web_extra_exposed_ports:
    - name: node-app
      container_port: 3000
      http_port: 3000
      https_port: 3001
```

Create this `.ddev/traefik/config/frontend.yaml` file:

```yaml
http:
  routers:
    example-web-80-http-frontend:
      entrypoints:
        - http-80
      rule: HostRegexp(`^frontend\.example\.ddev\.site$`)
      service: "example-web-3000"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "example-redirectHttps"
      priority: 100

    example-web-80-https-frontend:
      entrypoints:
        - http-443
      rule: HostRegexp(`^frontend\.example\.ddev\.site$`)
      service: "example-web-3000"
      ruleSyntax: v3
      tls: true
      priority: 100
```

**Comment by ayalon** [comment]
Thank you for the example. That is very helpful!

**Comment by rfay** [comment]
Nice! 

You wouldn't even need the `web_extra_exposed_ports` for anything but using port 3000 would you? Isn't that just extra, with all the real work being done by traefik config?

I should have mentioned the traefik approach.

**Comment by ayalon** [comment]
I don't need the port 3000 to be exposed at all. It would be enough to just have traefik catching my subdomain frontend.example and then proxy the request to th webcontainer.

I agree that maybe the is not needed at all. I will test it out.
```
`web_extra_exposed_ports:
  - name: "node-app"
    container_port: 3000
    http_port: 3000
    https_port: 3001`
```

**Comment by stasadev** [comment]
> You wouldn't even need the `web_extra_exposed_ports` for anything but using port 3000 would you? Isn't that just extra, with all the real work being done by traefik config?

I think it's true, in this case we want to define the `service: "example-web-3000"`, similar to others in `.ddev/traefik/config/<project-name>.yaml`

**Comment by ayalon** [comment]
I have tested it. The example is almost complete:`

```
http:
  routers:
    example-web-80-http-frontend:
      entrypoints:
        - http-80
      rule: HostRegexp(`^frontend\.example\.ddev\.site$`)
      service: "example-web-3000"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "example-redirectHttps"
      priority: 100

    example-web-80-https-frontend:
      entrypoints:
        - http-443
      rule: HostRegexp(`^frontend\.example\.ddev\.site$`)
      service: "example-web-3000"
      ruleSyntax: v3
      tls: true
      priority: 100
  services:
     example-web-3000:
      loadbalancer:
        servers:
          - url: http://ddev-example-web:3000

```

I also had to define the service, then it worked as expected. Many thanks for your dedication on DDEV. Really appreciate all the things you have created to make my life easier every day.
