### ISSUE TITLE
Automatically add subdomain for web exposed ports

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev#7208]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

I recently tried the guide at https://ddev.com/blog/ddev-expose-node-app-on-subdomain/ and it worked well.
Great job @ayalon!

It would be nice if DDEV could automatically do this for me, if provided with a subdomain. 

### Describe your solution

What I want to do is add the following `config.storybook.yaml` file to a `my-project` project.
And DDEV would automagically expose `storybook.my-project.ddev.site

```yml
web_extra_exposed_ports:
  - name: storybook
    container_port: 6006
    http_port: 6007
    https_port: 6006
    subdomain: storybook
```

The new subdomain should be displayed in `ddev status`

```shell
$ ddev status
...
├────────┼──┼─────────────────────────────────┤
│ storybook    │      │ https://my-project.ddev.site:6006                               │ 
│                     │      │ InDocker: web:6006                                                     │ 
│                     │      │ https://storybook.my-project.ddev.site                       │ 
├────────┼──┼─────────────────────────────────┤
```

### Describe alternatives

I considered reusing the `name` field, but that would add DNS constraints to the field.

It would also suddenly create the subdomain for all projects that expose ports as developers updated DDEV. 
Having it as an opt-in will help the feature mature with minimal impact.

**Comment by stasadev** [comment]
I've been thinking about this for a while, and here's what I suggest:

Using only a single `subdomain` is not flexible enough, I believe people will soon ask for more options. So, we should support both `additional_hostnames` and `additional_fqdns`, like this:

```yaml
name: example
web_extra_exposed_ports:
  - name: storybook
    container_port: 6006
    http_port: 6007
    https_port: 6006
    additional_hostnames:
      - subdomain.example
    additional_fqdns:
      - my-domain.test
```

Also, if I just want a subdomain and *don't* want the port exposed outside, that should be possible too:

```yaml
web_extra_exposed_ports:
  - name: storybook
    container_port: 6006
    additional_hostnames:
      - subdomain.example
```

Secondly, related to #5486, I'd like to avoid repeating the main domain in `additional_hostnames`. This should be possible with this (which is not currently supported):

```yaml
additional_hostnames:
  - subdomain.$DDEV_SITENAME
  - another-subdomain.${DDEV_SITENAME}
```

(This would be a really valuable feature especially in cases where the `name` is omitted from `.ddev/config.yaml`.)

---

P.S. An alternative idea would be to allow port specification directly within `additional_hostnames` and `additional_fqdns`:

```yaml
additional_hostnames:
  - subdomain.example:5000
additional_fqdns:
  - my-domain.test:5000
```

This would map container port `5000` to `subdomain.example.ddev.site` and `my-domain.test`. However, this approach is probably too implicit and could cause confusion, so I decided against it.

---

P.P.S. I'd love to hear alternative approaches or suggestions.
