### ISSUE TITLE
Option to add extra volume mounts to web

### ISSUE THREAD

**Issue by coredevel** [ddev/ddev#7254]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

No

### Describe your solution

Option to add /home/{user}/.vscode-server-insiders (or vscode) as an extra volume mount so on attaching vs code to dev (web) container the extensions and vs code server aren't installed each time which is kinda annoying. Thanks.

**Comment by tyler36** [comment]
@coredevel  That's an interesting idea.

You could try and play around with it by creating a `.ddev/docker-compose.vscode.yaml`

```yml
services:
  web:
    volumes:
      - "$HOME/.vscode-server:/home/$USERNAME/.vscode-server/"
```
