### ISSUE TITLE
support for .NET

### ISSUE THREAD

**Issue by kiquenet** [ddev/ddev#7400]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

support for .NET 

### Describe your solution

only support php and nodejs now ?

**Comment by rfay** [comment]
If you're interested in .net, see if you can experiment with the [generic webserver_type](https://ddev.readthedocs.io/en/stable/users/configuration/config/#webserver_type), as is demonstrated in the [frankenphp](https://ddev.readthedocs.io/en/stable/users/quickstart/#generic-frankenphp) and [nodejs](https://ddev.readthedocs.io/en/stable/users/quickstart/#nodejs) examples in the quickstarts.

We'd love to hear what you come up with, and would welcome a guest blog.

**Comment by rfay** [comment]
People have been successful with python and ruby... I don't see why you wouldn't be able to use the generic webserver type. Closing this for now, but happy to continue the conversation here or elsewhere.

**Comment by yanniboi** [comment]
I have a proof of concept as an add-on. It modifies the web container by changing the base image. It would be pretty cool to see if we could support some of these changes directly as a new project type.

https://github.com/FreelyGive/ddev-dotnet

The below does almost everything we need. It would be nice to be able to also remove mailpit as that makes no sense in a non-php server world.

```
type: generic
docroot: ""
webserver_type: generic
omit_containers: [db, ddev-ssh-agent]
web_extra_exposed_ports:
  - name: web
    container_port: 5000
    http_port: 80
    https_port: 443
```

There are a couple of hacks I need to do in a pre.Dockerfile as they are directories that are assumed to exist on the base image, but dont on a dotnet image:

https://github.com/FreelyGive/ddev-dotnet/blob/main/web-build/pre.Dockerfile
